### PR TITLE
Use less strict isolation level for channel meta

### LINKED ISSUE #1786: Node crash due to Postgres
Node failure due to `Cannot check database lease`. Multiple times, didn't notice this issue with default Postgres configs.

Maybe it would be good for node to not crash and just reject some operations with channels?

It repeats regularly, recently it lead to channel force-close.

Self-compiled. "0.5.1-98bb7be"

Linux Debian 10. OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)

I had config
```
eclair.db.postgres.lease {
    interval = 60 seconds        // Default: 5 minutes
    renew-interval =  30 seconds // Default: 1 minute
}
```
I made lease times shorter for faster node restarts. What is suggested time intervals?

```
2021-05-05 16:36:41,615 ERROR f.a.eclair.db.Databases - fatal error: Cannot obtain lock on the database.
fr.acinq.eclair.db.pg.PgUtils$LockException: Cannot check database lease
	at fr.acinq.eclair.db.pg.PgUtils$.fr$acinq$eclair$db$pg$PgUtils$$checkDatabaseLease(PgUtils.scala:211)
	at fr.acinq.eclair.db.pg.PgUtils$LeaseLock.$anonfun$withLock$1(PgUtils.scala:94)
	at fr.acinq.eclair.db.pg.PgUtils$.inTransaction(PgUtils.scala:106)
	at fr.acinq.eclair.db.pg.PgUtils$.$anonfun$inTransaction$1(PgUtils.scala:121)
	at fr.acinq.eclair.db.jdbc.JdbcUtils.withConnection(JdbcUtils.scala:35)
	at fr.acinq.eclair.db.jdbc.JdbcUtils.withConnection$(JdbcUtils.scala:32)
	at fr.acinq.eclair.db.pg.PgUtils$.withConnection(PgUtils.scala:30)
	at fr.acinq.eclair.db.pg.PgUtils$.inTransaction(PgUtils.scala:120)
	at fr.acinq.eclair.db.pg.PgUtils$LeaseLock.withLock(PgUtils.scala:92)
	at fr.acinq.eclair.db.pg.PgChannelsDb.$anonfun$addOrUpdateChannel$1(PgChannelsDb.scala:53)
	at fr.acinq.eclair.db.Monitoring$Metrics$.$anonfun$withMetrics$1(Monitoring.scala:33)
	at fr.acinq.eclair.KamonExt$.time(PimpKamon.scala:28)
	at fr.acinq.eclair.db.Monitoring$Metrics$.withMetrics(Monitoring.scala:31)
	at fr.acinq.eclair.db.pg.PgChannelsDb.addOrUpdateChannel(PgChannelsDb.scala:53)
	at fr.acinq.eclair.channel.Channel$MyState.storing(Channel.scala:2434)
	at fr.acinq.eclair.channel.Channel$$anonfun$9.applyOrElse(Channel.scala:774)
	at fr.acinq.eclair.channel.Channel$$anonfun$9.applyOrElse(Channel.scala:656)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at fr.acinq.eclair.channel.Channel$$anonfun$handleExceptions$1.applyOrElse(Channel.scala:2415)
	at fr.acinq.eclair.channel.Channel$$anonfun$handleExceptions$1.applyOrElse(Channel.scala:2412)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at akka.actor.FSM.processEvent(FSM.scala:804)
	at akka.actor.FSM.processEvent$(FSM.scala:801)
	at fr.acinq.eclair.channel.Channel.processEvent(Channel.scala:103)
Caused by: org.postgresql.util.PSQLException: ERROR: could not serialize access due to read/write dependencies among transactions
  Detail: Reason code: Canceled on identification as a pivot, during conflict out checking.
  Hint: The transaction might succeed if retried.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:313)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:226)
	at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:111)
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java)
	at fr.acinq.eclair.db.pg.PgUtils$.$anonfun$getCurrentLease$1(PgUtils.scala:221)
	at fr.acinq.eclair.db.jdbc.JdbcUtils.using(JdbcUtils.scala:50)
	at fr.acinq.eclair.db.jdbc.JdbcUtils.using$(JdbcUtils.scala:46)
	at fr.acinq.eclair.db.pg.PgUtils$.using(PgUtils.scala:30)
	at fr.acinq.eclair.db.pg.PgUtils$.getCurrentLease(PgUtils.scala:220)
	at fr.acinq.eclair.db.pg.PgUtils$.$anonfun$checkDatabaseLease$1(PgUtils.scala:197)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.Try$.apply(Try.scala:210)
	at fr.acinq.eclair.db.pg.PgUtils$.fr$acinq$eclair$db$pg$PgUtils$$checkDatabaseLease(PgUtils.scala:197)
	at fr.acinq.eclair.db.pg.PgUtils$LeaseLock.$anonfun$withLock$1(PgUtils.scala:94)
	at fr.acinq.eclair.db.pg.PgUtils$.inTransaction(PgUtils.scala:106)
	at fr.acinq.eclair.db.pg.PgUtils$.$anonfun$inTransaction$1(PgUtils.scala:121)
	at fr.acinq.eclair.db.jdbc.JdbcUtils.withConnection(JdbcUtils.scala:35)
```

@rorp

### PR DESCRIPTION
**Pull request by pm47**
We don't need `SERIALIZABLE` consistency guarantees when all we do is
updating timestamp columns. This happens concurrently to channel data
update and raised serialization errors in postgres.

Fixed #1786.

### CODE REVIEW

File: eclair-core/src/test/scala/fr/acinq/eclair/db/ChannelsDbSpec.scala [hunk 1]
```diff
@@ -98,8 +98,11 @@ class ChannelsDbSpec extends AnyFunSuite {
       val db = dbs.channels
       implicit val ec: ExecutionContextExecutor = ExecutionContext.fromExecutor(Executors.newFixedThreadPool(8))
       val channel = ChannelCodecsSpec.normal
-      val futures = for (_ <- 0 until 10000) yield {
-        Future(db.addOrUpdateChannel(channel.modify(_.commitments.channelId).setTo(randomBytes32)))
+      val channelIds = (for(_ <- 0 until 10) yield randomBytes32).toList
```
Comment (t-bast) [inline eclair-core/src/test/scala/fr/acinq/eclair/db/ChannelsDbSpec.scala:101]: nit:
```suggestion
      val channelIds = (0 until 10).map(_ => randomBytes32).toList
```

**Review by t-bast — APPROVED** [review]

**Review by t-bast — APPROVED** [review]
