### PR TITLE
Fix encoding of failure messages (fixes #363)

### LINKED ISSUE #363: Unable to decode onion error message from eclair to lnd
Lately, when I've been trying to send to/through starblocks on some of my nodes, my HTLC's keep getting rejected. I haven't been able to determine _why_ exactly, as I can't decode the error message sent by eclair: 
```
2018-01-08 03:31:50.032 [DBG] PEER: Received UpdateFailHTLC(chan_id=04c37f4471d3e994c1bb455b9cb976959149e0b9bda1a0d377a2df14574c2e36, id=146, reason=06345bbb0e4e0d441abbd994c3713ee43c409b1856b9727b3b518f123d4b5eaf3f0272ddf0b44355951d71bc1fc61b0fbd6a1ba9cc5ab1591f1319f1230d244f61537ea925115271f2aac7b92298b35b7cc88cca6581ed44596cc58196e7111e53647863986acee00e0bd007335c373d82e6544476cdd44b7b0a0b1152d03aad40abf562e235ba7770c55244198e35640be0bed4ca91d8f472c39bdc820616b01a487e71ab7d858a63b9d1ed4f2a12715e1e488769b4cb055f6da10bf19ad3e46644cb6ad0572e140657516ec32ac7cc40b1b969773e16fcae505e946f249b3f3095abf810790bdb5720c576ce433917b76ed70d1b046a09741f3b032d7da4ce877ecdb2939891d56896a1381cafacf276a4bbe0209880d901ed98fc0520bada9225261c) from 
2018-01-08 03:31:50.043 [DBG] PEER: Received CommitSig(chan_id=04c37f4471d3e994c1bb455b9cb976959149e0b9bda1a0d377a2df14574c2e36, num_htlcs=0) from 
2018-01-08 03:31:50.050 [DBG] PEER: Sending RevokeAndAck(chan_id=04c37f4471d3e994c1bb455b9cb976959149e0b9bda1a0d377a2df14574c2e36, rev=4564ef7c7de66b5348820f993ab18cc21d4e11c1a8327518ccd4a596fe484e87, next_point=037346b4c008d039b46a2f577d4833a80133d91a29af1e03ae62e0fb191b571126) to 2018-01-08 03:31:50.059 [DBG] PEER: Sending CommitSig(chan_id=04c37f4471d3e994c1bb455b9cb976959149e0b9bda1a0d377a2df14574c2e36, num_htlcs=0) to 
2018-01-08 03:31:50.162 [DBG] PEER: Received RevokeAndAck(chan_id=04c37f4471d3e994c1bb455b9cb976959149e0b9bda1a0d377a2df14574c2e36, rev=379f27413b8a5154a4731a44a2d261368ce69885c363c4032e0a1af5bb6ae2f3, next_point=037b81d3eceb4fdfd3fca0fb8dad244ce1e670ee339266836a548ca5868221c5ab) from 
2018-01-08 03:31:50.165 [DBG] HSWC: ChannelPoint(372e4c5714dfa277d3a0a1bdb9e049919576b99c5b45bbc194e9d371447fc304:1) forwarding 1 HTLC's
2018-01-08 03:31:50.165 [DBG] HSWC: Closed completed onion circuit for 7740f2c4715c705ab2d0211d06ae67a37fa0e95338e8f73d7f424fb13ab86604: (0:0:0, 220) <-> (1257786:147:1, 146)
2018-01-08 03:31:50.168 [ERR] HSWC: unable to de-obfuscate onion failure, htlc with hash(7740f2c4715c705ab2d0211d06ae67a37fa0e95338e8f73d7f424fb13ab86604): unable to decode error update (type=*lnwire.FailTemporaryChannelFailure, len_bytes=130, bytes=1007b42a4030b07a3f456093a3020b980c1f54a7b15d663d122360823091945ac55d6941f4e3c0bccc2339020993008ac4024c6af59d9a4a4074b3f12fb1fae93a1543497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea3309000000001329ca00006200005a526d580001009000000000000027100000271000000064): unexpected EOF
```

`lnd` determines it's a `FailTemporaryChannelFailure`, then tries to decode the message: 
```
1007b42a4030b07a3f456093a3020b980c1f54a7b15d663d122360823091945ac55d6941f4e3c0bccc2339020993008ac4024c6af59d9a4a4074b3f12fb1fae93a1543497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea3309000000001329ca00006200005a526d580001009000000000000027100000271000000064
```

Are y'all able to decode this?

### PR DESCRIPTION
**Pull request by sstone**
When a failure message includes a channel update field, this field must be encoded as:
[ len | channel update]
And we did not include the len field.

### CODE REVIEW

File: eclair-core/src/main/scala/fr/acinq/eclair/wire/FailureMessage.scala [hunk 1]
```diff
@@ -57,15 +59,15 @@ object FailureMessageCodecs {
...
     .typecase(PERM | 9, provide(RequiredChannelFeatureMissing))
     .typecase(PERM | 10, provide(UnknownNextPeer))
-    .typecase(UPDATE | 11, (("amountMsat" | uint64) :: ("channelUpdate" | channelUpdateCodec)).as[AmountBelowMinimum])
-    .typecase(UPDATE | 12, (("amountMsat" | uint64) :: ("channelUpdate" | channelUpdateCodec)).as[FeeInsufficient])
-    .typecase(UPDATE | 13, (("expiry" | uint32) :: ("channelUpdate" | channelUpdateCodec)).as[IncorrectCltvExpiry])
-    .typecase(UPDATE | 14, (("channelUpdate" | channelUpdateCodec)).as[ExpiryTooSoon])
-    .typecase(UPDATE | 20, (("flags" | binarydata(2)) :: ("channelUpdate" | channelUpdateCodec)).as[ChannelDisabled])
+    .typecase(UPDATE | 11, (("amountMsat" | uint64) :: ("channelUpdate" | channelUpdateWithLengthCodec)).as[AmountBelowMinimum])
+    .typecase(UPDATE | 12, (("amountMsat" | uint64) :: ("channelUpdate" | channelUpdateWithLengthCodec)).as[FeeInsufficient])
+    .typecase(UPDATE | 13, (("expiry" | uint32) :: ("channelUpdate" | ("channelUpdate" | variableSizeBytes(uint16, channelUpdateCodec)))).as[IncorrectCltvExpiry])
```
Comment (pm47) [inline eclair-core/src/main/scala/fr/acinq/eclair/wire/FailureMessage.scala]: > .typecase(UPDATE | 13, (("expiry" | uint32) :: ("channelUpdate" | ("channelUpdate" | variableSizeBytes(uint16, channelUpdateCodec)))).as[IncorrectCltvExpiry])

seems wrong
