### PR TITLE
Ignore non-relayed incoming HTLCs when closing

### LINKED ISSUE #2669: Broken channel: stuck in CLOSING
Somehow one of my channels got into a broken state.
The channel was force closed about 2 months ago and I just recently realised it was still in state “CLOSING”

When checking the closing TX, one can see that 5 HTLCs are still not swept.
https://mempool.space/tx/0bc06099220216e3a49b2cfad5220704b538eccc6fe406f2dc8ee9788f367244

Each time I restart my node I can see those lines in my log:

```
2023-05-21 17:07:14,954 WARN  f.a.e.c.fsm.Channel n:0396f85d0826607b5ce1c8eaffaee0f30cd224349f2c75a0ea8dd87d00bb77e59f c:aac6edaa182ed25592e7c491f87b2f8c97e3e777bd825847cd0292ff2656e09c - unknown htlc id=16102 while processing cmd=CMD_FAIL_HTLC in state=CLOSING
2023-05-21 17:07:14,954 WARN  f.a.e.c.fsm.Channel n:0396f85d0826607b5ce1c8eaffaee0f30cd224349f2c75a0ea8dd87d00bb77e59f c:aac6edaa182ed25592e7c491f87b2f8c97e3e777bd825847cd0292ff2656e09c - unknown htlc id=16107 while processing cmd=CMD_FAIL_HTLC in state=CLOSING
2023-05-21 17:07:14,954 WARN  f.a.e.c.fsm.Channel n:0396f85d0826607b5ce1c8eaffaee0f30cd224349f2c75a0ea8dd87d00bb77e59f c:aac6edaa182ed25592e7c491f87b2f8c97e3e777bd825847cd0292ff2656e09c - unknown htlc id=16108 while processing cmd=CMD_FAIL_HTLC in state=CLOSING
2023-05-21 17:07:14,954 WARN  f.a.e.c.fsm.Channel n:0396f85d0826607b5ce1c8eaffaee0f30cd224349f2c75a0ea8dd87d00bb77e59f c:aac6edaa182ed25592e7c491f87b2f8c97e3e777bd825847cd0292ff2656e09c - unknown htlc id=13886 while processing cmd=CMD_FAIL_HTLC in state=CLOSING
2023-05-21 17:07:14,955 WARN  f.a.e.c.fsm.Channel n:0396f85d0826607b5ce1c8eaffaee0f30cd224349f2c75a0ea8dd87d00bb77e59f c:aac6edaa182ed25592e7c491f87b2f8c97e3e777bd825847cd0292ff2656e09c - unknown htlc id=16109 while processing cmd=CMD_FULFILL_HTLC in state=CLOSING

```
Here is the channel data for that channel:
[782367x516x1.txt](https://github.com/ACINQ/eclair/files/11543147/782367x516x1.txt)

Eclair version: version=0.8.0 commit=0077471

### PR DESCRIPTION
**Pull request by t-bast**
If we force-close with HTLCs that have just been signed by our peer but for which we haven't received their revocation, we should ignore them. We have not relayed those HTLCs so they can't be fulfilled. It is our peer's responsibility to claim them on-chain (using their HTLC-timeout), but if for some reason they don't claim it, we don't want the channel to be stuck in the closing state.

This is a subtle and dangerous change, please review carefully!

Note that we don't fix existing channels that are already in that state (they will have an entry `Outpoint -> None` in `localCommitPublished.htlcTxs`). It is a bit dangerous to fix them automatically, I'd rather either wait for the peer to claim the HTLC on-chain or let impacted node operators (only @DerEwige as far as I know) manually fix it by running the following DB commands (while their eclair node is stopped, before restarting it).

For sqlite:

```
DELETE FROM pending_settlement_commands WHERE channel_id=X'<channel_id_hex_string>'
DELETE FROM htlc_infos WHERE channel_id=X'<channel_id_hex_string>'
UPDATE local_channels SET is_closed=1 WHERE channel_id=X'<channel_id_hex_string>'

Example for the channel in issue 2669:
DELETE FROM pending_settlement_commands WHERE channel_id=X'aac6edaa182ed25592e7c491f87b2f8c97e3e777bd825847cd0292ff2656e09c'
DELETE FROM htlc_infos WHERE channel_id=X'aac6edaa182ed25592e7c491f87b2f8c97e3e777bd825847cd0292ff2656e09c'
UPDATE local_channels SET is_closed=1 WHERE channel_id=X'aac6edaa182ed25592e7c491f87b2f8c97e3e777bd825847cd0292ff2656e09c'
```

For postgres:

```
DELETE FROM local.pending_settlement_commands WHERE channel_id='<channel_id_hex_string>'
DELETE FROM local.htlc_infos WHERE channel_id='<channel_id_hex_string>'
UPDATE local.channels SET is_closed=TRUE WHERE channel_id='<channel_id_hex_string>'

Example for the channel in issue 2669:
DELETE FROM local.pending_settlement_commands WHERE channel_id='aac6edaa182ed25592e7c491f87b2f8c97e3e777bd825847cd0292ff2656e09c'
DELETE FROM local.htlc_infos WHERE channel_id='aac6edaa182ed25592e7c491f87b2f8c97e3e777bd825847cd0292ff2656e09c'
UPDATE local.channels SET is_closed=TRUE WHERE channel_id='aac6edaa182ed25592e7c491f87b2f8c97e3e777bd825847cd0292ff2656e09c'
```

Fixes #2669

### CODE REVIEW

File: eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala [hunk 1]
```diff
@@ -792,6 +792,8 @@ object Helpers {
           case u: UpdateFailHtlc => u.id
           case u: UpdateFailMalformedHtlc => u.id
         }.toSet
+        // these htlcs have been signed by our peer, but we haven't received their revocation and relayed them yet
+        val nonRelayedIncomingHtlcs: Set[Long] = commitment.changes.remoteChanges.signed.collect { case add: UpdateAddHtlc => add.id }.toSet
```
Comment (pm47) [inline eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala:796]: Analysis:

An incoming htlc always follows this signature path:
1. receive `UpdateAddHtlc`: add htlc to `remoteChanges.proposed`
2. receive `CommitSig`, send `RevokeAndAck`: move htlc from `remoteChanges.proposed` -> `remoteChanges.acked`
3. send `CommitSig`: move htlc from `remoteChanges.acked` -> `remoteChanges.signed`
4. receive `RevokeAndAck`: remove htlc from `remoteChanges.signed`

This is why we only relay an incoming htlc when we receive remote's revocation:
https://github.com/ACINQ/eclair/blob/835b33b2b8ab6e39ff87fff652b880b19a5a2c8f/eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala#L580

However, starting from step 2., the htlc is already in our local commitment.

So, we should also ignore htlcs that are in `remoteChanges.acked`. In fact, we could take all htlcs in `remoteChanges`, which may be conceptually simpler:

```suggestion
        val nonRelayedIncomingHtlcs: Set[Long] = commitment.changes.remoteChanges.all.collect { case add: UpdateAddHtlc => add.id }.toSet
```

**Review by pm47 — CHANGES_REQUESTED** [review]

File: eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala (hunk 1 above)
Comment (t-bast) [reply eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala]: Good point, I agree! This is harder to test though, because we immediately do step 2 and 3 without an opportunity to stop the channel FSM in between, but the existing test is probably already good enough.

Done in https://github.com/ACINQ/eclair/pull/2672/commits/782c8f85381558f9f94020fd347d83ae8e734f1c

**Review by pm47 — APPROVED** [review]
