### PR TITLE
Set a minimum feerate-per-kw of 253 (fixes #602)

### LINKED ISSUE #602: Channel stuck in Closing due to "cannot publish tx: reason=66: min relay fee not met (code: -26)"
I had a few channels that were closed due to fee issues.

They had small incoming balances (904 satoshi in this case).
When it came to publish the toLocal timeout tx from commitment tx that was published we get this error:

`eclairdebug.2018-05-18.log:16:01:25.354 ERROR akka://default/user/$b/watcher f.a.e.blockchain.bitcoind.ZmqWatcher - cannot publish tx: reason=66: min relay fee not met (code: -26) txid=8724c404a4a0dc4846368c04236d56639098455e01fddfd477314d033ade73e0 tx=02000000000101a5c3d4efb0df5b2c5440f77d990270572878e91b2df0e958147fc4760f348bb00000000000f000000001100300000000000017a914afedceb5c9733c5a7505d4b520d123dd1fc5ffda870347304402202b53435cf524ac48187fbd095d8180ce40bc3111b162641facc0d616b91a14f502203f3e9a3602dfb62564e63b0044fa0fc1d1115ef3e32da673dafb79534d22258101004d632102ced73eacd36a1f801b4b4291ea16eddb174eca44dd247d6b77a1bcba9b50598e6702f000b275210290bc851d23c11be5629d532d0cce7051171ec0e1cb39369b6581f80a18ee0ee868ac00000000`

Which makes sense. As is below the default of 0.00001 - 1000 sat btc/kb which is what my btcd is running with.
This tx has 120 Sat fee.  which is 506 Sat/KByte - hence why not relayed.

### PR DESCRIPTION
**Pull request by sstone**
We currently use feerate-per-kw = feerate-per-kb / 4, which gives 250 for 1000 sat/kb, which can result in transactions that are below the minimum relay fee of 1000 sat/kb.
This is because bitcoin core checks minimum relay fees using a transaction's virtual size (and not its actual size in bytes).
So we want :
    fee > 1000 * virtual size
    feerate-per-kw * weight > 1000 * (3 * weight / 4)
    feerate_per-kw > 250 + 3000 / (4 * weight)
    
With a conservative minimum weight of 400, we get a minimum feerate_per-kw of 253

### CODE REVIEW

**Comment by n1bor** [comment]
Will having minimum fee of 2 instead of 1 cause issues interacting with lnd etc..? As will not agree a common fee as 2x difference?

**Comment by sstone** [comment]
No it should no (but it's a good point). lnd is already very lax when validating fee updates, and c-lightning should be pretty soon. Basically it is nearly impossible to agree on onchain fees unless nodes check the same estimator at exactly the same time, so nodes should accept fee rates that are very different from them (as long as txs remain publishable of course).

**Comment by n1bor** [comment]
I would never have expected 6 months ago the biggest issues would have been around fees! But I think has been the cause of most of the issues I have had running a node!

File: eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForOpenChannelStateSpec.scala [hunk 1]
```diff
@@ -125,16 +125,30 @@ class WaitForOpenChannelStateSpec extends TestkitBaseClass with StateTestsHelper
...
   }
 
-  test("recv OpenChannel (fee too low)") { case (bob, alice2bob, bob2alice, _) =>
+  test("recv OpenChannel (fee too low, but still valid)") { case (bob, alice2bob, bob2alice, _) =>
     within(30 seconds) {
       val open = alice2bob.expectMsgType[OpenChannel]
       // set a very small fee
-      val tinyFee = 100
+      val tinyFee = 254
       bob ! open.copy(feeratePerKw = tinyFee)
```
Comment (dpad85) [inline eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForOpenChannelStateSpec.scala]: Should be the tiniest possible aka 253

File: eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala [hunk 2]
```diff
@@ -251,124 +263,183 @@ object Transactions {
...
     val outputIndex = findPubKeyScriptIndex(commitTx, pubkeyScript, outputsAlreadyUsed, amount_opt = Some(Satoshi(htlc.amountMsat / 1000)))
     val input = InputInfo(OutPoint(commitTx, outputIndex), commitTx.txOut(outputIndex), write(redeemScript))
+
+    val tx = Transaction(
+      version = 2,
+      txIn = TxIn(input.outPoint, Array.emptyByteArray, 0xffffffffL) :: Nil,
+      txOut = TxOut(Satoshi(0), localFinalScriptPubKey) :: Nil,
+      lockTime = 0)
+
+    val weight = Transactions.addSigs(ClaimHtlcTimeoutTx(input, tx), BinaryData("00" * 73)).tx.weight()
```
Comment (dpad85) [inline eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala]: Should be `ClaimHtlcSuccessTx`

**Comment by mautematico** [comment]
On my (testnet beta4) wallet, I have only one UTXO of 10100000 satoshi.

Since this PR was merged, whenever I try to open a channel, on-chain fee is always 253+

`eclair-cli open 031303e0dca4e544c08e78e47242bc21a080b0acbfa249e34eb78804ae7776b9f6 10100000 0 1`

`fundingSatoshis=Satoshi(10100000), pushMsat=MilliSatoshi(0) and fundingFeeratePerByte=Some(253)`


What is more interesting, tough, is the fact that when satPerByte is bigger than 1, funding fee becomes multiple of 250.

`eclair-cli open 031303e0dca4e544c08e78e47242bc21a080b0acbfa249e34eb78804ae7776b9f6 10100000 0 1000`
`with fundingSatoshis=Satoshi(10100000), pushMsat=MilliSatoshi(0) and fundingFeeratePerByte=Some(250000)`

`eclair-cli open 031303e0dca4e544c08e78e47242bc21a080b0acbfa249e34eb78804ae7776b9f6 10100000 0 1000`
`with fundingSatoshis=Satoshi(10100000), pushMsat=MilliSatoshi(0) and fundingFeeratePerByte=Some(500)`


Both are misscalculations.

Please inspect this tx (I did it with electrum):

02000000000101f2a48432b83a0de9d189278b7acf856031777aad748f75920c10de248b7269f900000000171600146c13b99bceb8d6a002e9e6001daa15b0b3257cf9ffffffff012c1b9a0000000000220020c86914ab4f7b89fae2e109466b6c98a46ac2da8b230c0f82278c062137e40ff60247304402204413f3ea30a2a2e2e1c5f0720acad7f4d282d6d63effb42b7bdd6e267f035f93022022d655446da173c1b1d45cd005c20c3f552890d2175a702894b04fb6774fa3ce012102f1907e2523daa9853c51c0bbd27eb8511dcc744ff387be33c007c02eaf0a832000000000


145 satoshi fee would be enough, but it is paying 500 satoshi; and this PR will only let you pay {253, 500, 750, ... } satoshi

**Comment by mautematico** [comment]
Also:

On 0.2-beta3, I was able to open channels paying total fee of 145 satoshi, as you can see here:

https://oxt.me/transaction/7fc48cee50bc1acda648aec8de36105165534acb07aee0e0827441a628d82b19

It was kind of tricky **_open publickey 501677 0 0_** in this particular case.
`501677+145` equals total UTXO balance.

**Comment by sstone** [comment]
What is logged is the fee rate that is currently used, not an amount in satoshis.
The point of this PR is so set a minimum fee *rate*, in satoshi/kw, not an absolute minimum fee in satoshi.  If you follow the LN spec, and translate a fee estimation of 1000 sat/kB into 250 sat/kw you end up with transactions that cannot be relayed because bitcoind checks fees in sat/vbyte.

**Comment by mautematico** [comment]
Hmm..

after this PR, I was unable to `open pubkey amount 0 1`; only after amount+253=total satoshi amount.

But again, this tx has a vBsize of 145, so 145 satoshi would be enough to realy it.

020000000001013661f724efc02582472949e1ce2159ddc49a123d738d083e70ee3952cd41b83900000000171600146c13b99bceb8d6a002e9e6001daa15b0b3257cf9ffffffff018395980000000000220020f56eb1a172556f1efc7744f668952dc1ec42fdf81832d06005797b15d18eac670247304402203e34263e374d037d2a878e199b694b2078f728280c5c18761b9995431963cf5102204a8ac10501d4d5c1f3fa4222e0f547028d349184d4392ca545558574d7af089d012102f1907e2523daa9853c51c0bbd27eb8511dcc744ff387be33c007c02eaf0a832000000000


So I think there is something wrong with calculation at some point.


Btw, if the whole issue is the wawy bitcoind checks fees, why don't we do the same (i.e. calculate fees in sat/vbyte)?
