### PR TITLE
Fail unsigned outgoing htlcs at CLOSING

### LINKED ISSUE #649: Expired payment not being failed by Endurance
I have two outgoing payments sent from `phone -> endurance -> ... -> lncast` which are expired by now but they are not being failed by `endurance`. My wallet should have closed a channel by now but I use a custom version which does not do that specifically to detect such cases.

Local peer id: `03cb7c2acef2d1509b12ad3d216036356a4947311c1c67237a50de64527fb66da8`
Remote peer id: `03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134`
Channel id: `2a2bd2255cad190ea80dde18cff1f384a14042ce4477c33850966f660f90b933`

Stuck payments hashes:
`216e58d46f264ec4ee1ad415dbb6b8fed6c0bcb1646bcfb205dff205d67f2436`
`1bb4f552c88642ed11b45813809708ae90d2634ad492639fb0c3f15d070cd512`

### PR DESCRIPTION
**Pull request by pm47**
This can happen in an unilateral close scenario, when local commit
"wins" the race to the blockchain, and some outgoing htlcs weren't yet
signed by remote.

This fixes #649.

### CODE REVIEW

File: eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala [hunk 1]
```diff
@@ -674,6 +674,25 @@ object Helpers {
...
+      *
+      * Those are only present in the remote's commitment.
+      *
+      * @param localCommit
+      * @param remoteCommit
+      * @param tx
+      * @param log
+      * @return
+      */
+    def overridenHtlcs(localCommit: LocalCommit, remoteCommit: RemoteCommit, tx: Transaction)(implicit log: LoggingAdapter): Set[UpdateAddHtlc] =
```
Comment (sstone) [inline eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala]: typo: overridden
