### PR TITLE
Electrum: improve coin selection (fixes #1146)

### LINKED ISSUE #1146: Electrum wallet: cannot fund tx is amount is close to the entire wallet balance
Wallets with only one utxo may fail to fund a transaction that sends all the available balance and the target fee rate is low, and will incorrectly return an `insufficient funds` error. 

See https://github.com/ACINQ/eclair-mobile/issues/211

### PR DESCRIPTION
**Pull request by sstone**
This PR changes how we select UTXOs when funding transactions, and fixes an issue where trying to use the amount returned by "spend all" with only 1 utxo and a low fee rate would result in an incorrect "insufficient funds" error (see #1146)

### CODE REVIEW

File: eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala [hunk 1]
```diff
@@ -971,35 +945,61 @@ object ElectrumWallet {
...
+      val tx1 = addUtxosWithDummySig(tx, selected)
+      val tx2 = change_opt.map(out => tx1.addOutput(out)).getOrElse(tx1)
       val tx3 = signTransaction(tx2)
-      //Transaction.correctlySpends(tx3, utxos.map(utxo => utxo.outPoint -> TxOut(Satoshi(utxo.item.value), computePublicKeyScript(utxo.key.publicKey))).toMap, ScriptFlags.STANDARD_SCRIPT_VERIFY_FLAGS)
 
-      // and add the completed tx to the lokcs
+      // and add the completed tx to the locks
       val data1 = this.copy(locks = this.locks + tx3)
-      val fee3 = spent - tx3.txOut.map(_.amount).sum
+      val fee = selected.map(s => Satoshi(s.item.value)).sum - tx3.txOut.map(_.amount).sum
```
Comment (t-bast) [inline eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala]: Why don't we put a `lazy val fee` inside `Transaction` that does that?
It seems like it's unnecessary to separately return the fee, it's a property of the `Transaction`.

File: eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala [hunk 2]
```diff
@@ -971,35 +945,61 @@ object ElectrumWallet {
...
 
-      // add change output only if non-dust, otherwise change is added to the fee
-      val (tx2, fee2, pos) = (spent - amount - fee1) match {
-        case dustChange if dustChange < dustLimit => (tx1, fee1 + dustChange, -1) // if change is below dust we add it to fees
-        case change => (tx1.addOutput(TxOut(change, computePublicKeyScript(currentChangeKey.publicKey))), fee1, 1) // change output index is always 1
+      val dummyChange = TxOut(Satoshi(0), computePublicKeyScript(currentChangeKey.publicKey))
+
+      @tailrec
+      def loop(current: Seq[Utxo], remaining: Seq[Utxo]) : (Seq[Utxo], Option[TxOut]) = {
+        totalAmount(current) match {
```
Comment (t-bast) [inline eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala]: nit: small proposal that makes it more obvious that each time we're calling `head` or `tail` we're sure we still have elements (can be ignored if you prefer your version):

```scala
totalAmount(current) match {
  case total if total - amount - computeFee(current, None) < Satoshi(0) && remaining.isEmpty => remaining match {
    // not enough funds to send amount and pay fees even without a change output
    case Nil => throw new IllegalArgumentException("insufficient funds")
    // not enough funds, try with an additional input
    case remaining => loop(remaining.head +: current, remaining.tail)
  }
  case total if total - amount - computeFee(current, None) <= dustLimit =>
    // change output would be below dust, we don't add one and just overpay fees
    (current, None)
  case total if total - amount - computeFee(current, Some(dummyChange)) <= dustLimit => remaining match {
    // change output is above dust limit but cannot pay for it's own fee, and we have no more utxos => we overpay a bit
    case Nil => (current, None)
    // try with an additional input
    case remaining => loop(remaining.head +: current, remaining.tail)
  }
  case total =>
    val fee = computeFee(current, Some(dummyChange))
    val change = dummyChange.copy(amount = total - amount - fee)
    (current, Some(change))
}
```

File: eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala [hunk 3]
```diff
@@ -971,35 +945,61 @@ object ElectrumWallet {
       val amount = tx.txOut.map(_.amount).sum
       require(amount > dustLimit, "amount to send is below dust limit")
 
-      // start with a hefty fee estimate
-      val utxos = chooseUtxos(amount + Transactions.weight2fee(feeRatePerKw, 1000), allowSpendUnconfirmed)
-      val spent = totalAmount(utxos)
+      // select utxos that are not locked by pending txs
+      val lockedOutputs = locks.map(_.txIn.map(_.outPoint)).flatten
```
[the remark this answers is not in the document]
Comment (sstone) [reply eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala]: :+1:

File: eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala (hunk 1 above)
Comment (sstone) [reply eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala]: Because a transaction cannot compute its onchain fees since it is missing the values of the UTXOs it is spending, it just know their outpoints.

File: eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala [hunk 4]
```diff
@@ -971,35 +945,61 @@ object ElectrumWallet {
...
-      // add change output only if non-dust, otherwise change is added to the fee
-      val (tx2, fee2, pos) = (spent - amount - fee1) match {
-        case dustChange if dustChange < dustLimit => (tx1, fee1 + dustChange, -1) // if change is below dust we add it to fees
-        case change => (tx1.addOutput(TxOut(change, computePublicKeyScript(currentChangeKey.publicKey))), fee1, 1) // change output index is always 1
+      val dummyChange = TxOut(Satoshi(0), computePublicKeyScript(currentChangeKey.publicKey))
+
+      @tailrec
+      def loop(current: Seq[Utxo], remaining: Seq[Utxo]) : (Seq[Utxo], Option[TxOut]) = {
+        totalAmount(current) match {
+          case total if total - amount - computeFee(current, None) < Satoshi(0) && remaining.isEmpty =>
```
[the remark this answers is not in the document]
Comment (sstone) [reply eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala]: :+!:

File: eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala (hunk 2 above)
Comment (sstone) [reply eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala]: It's highly subjective for I find the current version with an explicit check on `remaining.isEmpty` easier to read

Comment (t-bast) [reply eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala]: Agreed that it's subjective, no need to take this into account if you prefer your version.

Comment (sstone) [reply eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala]: :+1:

File: eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala (hunk 1 above)
Comment (t-bast) [reply eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala]: Indeed, the outpoint doesn't have enough information to compute this, my bad.
