### PR TITLE
Check blockchain watchdogs regularly

### LINKED ISSUE #1803: BlockchainWatchdog doesn't work independently
I open this issue because of suggestion made by Anton.

The issue revealed as a result of other problems https://github.com/ACINQ/eclair/issues/1789.

In particular, I noticed that when ZMQ actor stops receiving blocks, BlockchainWatchdog also stops working and counting how many blocks node missed with regard to explorers.

### PR DESCRIPTION
**Pull request by t-bast**
We want to check secondary blockchain sources when we haven't received blocks in a while.
Thanks @engenegr and @btcontract for raising this.

Fixes #1803

### CODE REVIEW

File: eclair-core/src/main/scala/fr/acinq/eclair/blockchain/watchdogs/BlockchainWatchdog.scala [hunk 1]
```diff
@@ -50,21 +51,29 @@ object BlockchainWatchdog {
...
+  def apply(chainHash: ByteVector32, maxRandomDelay: FiniteDuration, blockTimeout: FiniteDuration = 15 minutes): Behavior[Command] = {
     Behaviors.setup { context =>
       context.system.eventStream ! EventStream.Subscribe(context.messageAdapter[CurrentBlockCount](cbc => WrappedCurrentBlockCount(cbc.blockCount)))
       Behaviors.withTimers { timers =>
+        // We start a timer to check blockchain watchdogs regularly even when we don't receive any block.
+        timers.startSingleTimer(NoBlockReceivedTimer, NoBlockReceivedSince(0), blockTimeout)
         Behaviors.receiveMessage {
+          case NoBlockReceivedSince(lastBlockCount) =>
+            context.self ! CheckLatestHeaders(lastBlockCount)
+            timers.startSingleTimer(NoBlockReceivedTimer, NoBlockReceivedSince(lastBlockCount), blockTimeout)
```
Comment (pm47) [inline eclair-core/src/main/scala/fr/acinq/eclair/blockchain/watchdogs/BlockchainWatchdog.scala:71]: Doc:

> if a new timer with same key is started the previous is cancelled.

So `timers.startSingleTimer` effectively resets the timer. ✔️

**Review by pm47 — APPROVED** [review]

File: eclair-core/src/main/scala/fr/acinq/eclair/blockchain/watchdogs/BlockchainWatchdog.scala (hunk 1 above)
Comment (t-bast) [reply eclair-core/src/main/scala/fr/acinq/eclair/blockchain/watchdogs/BlockchainWatchdog.scala:71]: Yes, that's why I chose the overload with a `key` ;)
