### PR TITLE
Broadcast commit tx when nothing at stake

### LINKED ISSUE #1730: Eclair may fail and delete a channel without broadcasting its last commitment
I am running eclair-node-0.5.1-98bb7be on my Eclair node (mainnet). 
I observed the same behavior with the ACINQ node.

I am trying to have Eclair force-close a channel, pretending to have lost state. I am sending `channel_reestablish` with `next_commitment_number=0`, `next_revocation_number=0`, `your_last_per_commitment_secret=32*0x00`, and `my_current_per_commitment_point` set to an arbitrary valid point.

Eclair does not broadcast its last commitment, if the channel has never been used and there is no `to_local` output. In addition, the log suggests that the channel was deleted from the database. This can lead to fund losses, if the user actually lost their state.

Eclair does force-close, however, if the channel has already been used to send 1 satoshi, (which is too low to create a `to_local` output). Thus, it looks like the issue may be related to the value of the current commitment number, and not to the presence of a to_local output.

Here is a log of my node when this happened. Of particular concern is the line that indicates that Eclair is deleting the database entry.

```
2021-03-18 09:34:03,102 INFO  f.a.e.io.PeerConnection CON - connection authenticated with 027d8ccdc5fd719d2703ab1a9f64c0b641e790eec334b44ce2bd17a40a87d9f4b5@95.91.208.104:52240 direction=incoming
2021-03-18 09:34:03,102 INFO  f.a.e.io.PeerConnection CON n:027d8ccdc5fd719d2703ab1a9f64c0b641e790eec334b44ce2bd17a40a87d9f4b5 - using features=payment_secret:optional,var_onion_optin:optional,basic_mpp:optiona\
l,option_support_large_channel:optional,gossip_queries_ex:optional,trampoline_payment:optional,option_data_loss_protect:optional,option_static_remotekey:optional,gossip_queries:optional
2021-03-18 09:34:03,103 INFO  f.a.e.io.PeerConnection CON n:027d8ccdc5fd719d2703ab1a9f64c0b641e790eec334b44ce2bd17a40a87d9f4b5 - peer is using features=payment_secret:optional,option_data_loss_protect:mandatory\
,var_onion_optin:optional,basic_mpp:optional,option_static_remotekey:optional,gossip_queries:mandatory,option_data_loss_protect:optional,option_static_remotekey:mandatory (unknown=5,25), networks=6fe28c0ab6f1b3\
72c1a6a246ae63f74f931e8365e15a089c68d6190000000000
2021-03-18 09:34:03,103 INFO  f.a.e.io.PeerConnection CON n:027d8ccdc5fd719d2703ab1a9f64c0b641e790eec334b44ce2bd17a40a87d9f4b5 - rebroadcast will be delayed by 38 seconds
2021-03-18 09:34:03,103 INFO  f.a.e.io.PeerConnection n:027d8ccdc5fd719d2703ab1a9f64c0b641e790eec334b44ce2bd17a40a87d9f4b5 - sending sync channel range query with flags_opt=None replacePrevious=true
2021-03-18 09:34:03,103 INFO  f.a.e.i.ReconnectionTask CON n:027d8ccdc5fd719d2703ab1a9f64c0b641e790eec334b44ce2bd17a40a87d9f4b5 - peer is connected
2021-03-18 09:34:03,103 INFO  f.a.e.i.Peer CON n:027d8ccdc5fd719d2703ab1a9f64c0b641e790eec334b44ce2bd17a40a87d9f4b5 c:a44d35c6db86a2907f44bbf76466a74aaa0a71d4fedb534b3c05720a37eb5d49 - OUT msg=ChannelReestablis\
h(a44d35c6db86a2907f44bbf76466a74aaa0a71d4fedb534b3c05720a37eb5d49,1,0,PrivateKey(0000000000000000000000000000000000000000000000000000000000000000),03720d02c194916ae0b356ddf0505d05aa208a8b7eec48cfe8789cf9f24e95\
9f3d)
2021-03-18 09:34:03,103 INFO  f.a.e.i.Peer CON n:027d8ccdc5fd719d2703ab1a9f64c0b641e790eec334b44ce2bd17a40a87d9f4b5 c:f56a5968a7bcb9c7fdc63a1e68dbe369b3b6cd962629d7d16411f3440a3ab5ae - OUT msg=ChannelReestablis\
h(f56a5968a7bcb9c7fdc63a1e68dbe369b3b6cd962629d7d16411f3440a3ab5ae,1,0,PrivateKey(0000000000000000000000000000000000000000000000000000000000000000),02371e8cdfc28440c108869a178f4044db6cff938c4f703b3e493a7feab5c0\
7b5f)
2021-03-18 09:34:03,103 INFO  f.a.eclair.Diagnostics CON n:027d8ccdc5fd719d2703ab1a9f64c0b641e790eec334b44ce2bd17a40a87d9f4b5 c:a44d35c6db86a2907f44bbf76466a74aaa0a71d4fedb534b3c05720a37eb5d49 - OUT msg=Channel\
Reestablish(a44d35c6db86a2907f44bbf76466a74aaa0a71d4fedb534b3c05720a37eb5d49,1,0,PrivateKey(0000000000000000000000000000000000000000000000000000000000000000),03720d02c194916ae0b356ddf0505d05aa208a8b7eec48cfe878\
9cf9f24e959f3d)
2021-03-18 09:34:03,104 INFO  f.a.eclair.Diagnostics CON n:027d8ccdc5fd719d2703ab1a9f64c0b641e790eec334b44ce2bd17a40a87d9f4b5 c:f56a5968a7bcb9c7fdc63a1e68dbe369b3b6cd962629d7d16411f3440a3ab5ae - OUT msg=Channel\
Reestablish(f56a5968a7bcb9c7fdc63a1e68dbe369b3b6cd962629d7d16411f3440a3ab5ae,1,0,PrivateKey(0000000000000000000000000000000000000000000000000000000000000000),02371e8cdfc28440c108869a178f4044db6cff938c4f703b3e49\
3a7feab5c07b5f)
2021-03-18 09:34:03,132 INFO  f.a.eclair.Diagnostics CON n:027d8ccdc5fd719d2703ab1a9f64c0b641e790eec334b44ce2bd17a40a87d9f4b5 c:a44d35c6db86a2907f44bbf76466a74aaa0a71d4fedb534b3c05720a37eb5d49 - IN msg=ChannelR\
eestablish(a44d35c6db86a2907f44bbf76466a74aaa0a71d4fedb534b3c05720a37eb5d49,0,0,PrivateKey(0000000000000000000000000000000000000000000000000000000000000000),02fe8d1eb1bcb3432b1db5833ff5f2226d9cb5e65cee430558c18\
ed3a3c86ce1af)
2021-03-18 09:34:03,198 INFO  f.a.e.i.Peer CON n:027d8ccdc5fd719d2703ab1a9f64c0b641e790eec334b44ce2bd17a40a87d9f4b5 c:a44d35c6db86a2907f44bbf76466a74aaa0a71d4fedb534b3c05720a37eb5d49 - IN msg=ChannelReestablish\
(a44d35c6db86a2907f44bbf76466a74aaa0a71d4fedb534b3c05720a37eb5d49,0,0,PrivateKey(0000000000000000000000000000000000000000000000000000000000000000),02fe8d1eb1bcb3432b1db5833ff5f2226d9cb5e65cee430558c18ed3a3c86ce\
1af)
2021-03-18 09:34:03,198 ERROR f.a.e.channel.Channel CON n:027d8ccdc5fd719d2703ab1a9f64c0b641e790eec334b44ce2bd17a40a87d9f4b5 c:a44d35c6db86a2907f44bbf76466a74aaa0a71d4fedb534b3c05720a37eb5d49 - commitment sync \
error while processing msg=String in state=SYNCING
2021-03-18 09:34:04,571 INFO  f.a.eclair.router.Router n:027d8ccdc5fd719d2703ab1a9f64c0b641e790eec334b44ce2bd17a40a87d9f4b5 - sending query_channel_range=QueryChannelRange(6fe28c0ab6f1b372c1a6a246ae63f74f931e83\
65e15a089c68d6190000000000,0,2147483647,TlvStream(List(),List()))
2021-03-18 09:34:13,143 INFO  f.a.e.channel.Channel n:027d8ccdc5fd719d2703ab1a9f64c0b641e790eec334b44ce2bd17a40a87d9f4b5 c:a44d35c6db86a2907f44bbf76466a74aaa0a71d4fedb534b3c05720a37eb5d49 - deleting database re\
cord for channelId=a44d35c6db86a2907f44bbf76466a74aaa0a71d4fedb534b3c05720a37eb5d49
2021-03-18 09:34:13,853 INFO  f.a.e.channel.Channel n:027d8ccdc5fd719d2703ab1a9f64c0b641e790eec334b44ce2bd17a40a87d9f4b5 c:a44d35c6db86a2907f44bbf76466a74aaa0a71d4fedb534b3c05720a37eb5d49 - shutting down
2021-03-18 09:34:13,854 INFO  fr.acinq.eclair.io.Peer n:027d8ccdc5fd719d2703ab1a9f64c0b641e790eec334b44ce2bd17a40a87d9f4b5 - channel closed: channelId=FinalChannelId(a44d35c6db86a2907f44bbf76466a74aaa0a71d4fedb\
534b3c05720a37eb5d49)

```

### PR DESCRIPTION
**Pull request by t-bast**
When we have nothing at stake (channel was never used and we don't have funds to claim), we previously directly went to the CLOSED state without publishing our commitment. This can be an issue for our peer if they have lost data or had a hard time getting a funding tx confirmed.

We now publish our commitment once to help them get their funds back in all cases and avoid the CSV delays when getting their funds back.

Fixes #1730

### CODE REVIEW

File: eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala [hunk 1]
```diff
@@ -268,8 +269,11 @@ class WaitForFundingConfirmedStateSpec extends TestKitBaseClass with FixtureAnyF
 
   test("recv Error (nothing at stake)", Tag(ChannelStateTestsTags.NoPushMsat)) { f =>
     import f._
+    val tx = bob.stateData.asInstanceOf[DATA_WAIT_FOR_FUNDING_CONFIRMED].commitments.localCommit.commitTxAndRemoteSig.commitTx.tx
     bob ! Error(ByteVector32.Zeroes, "funding double-spent")
-    bob2blockchain.expectNoMessage(100 millis) // we don't publish our commit tx when we have nothing at stake
+    // We have nothing at stake, but we publish our commitment to help our peer recover their funds more quickly.
```
Comment (sstone) [inline eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala:274]: nit: the error that is sent could now use a more generic message ("double-spent" may be a bit confusing)

**Review by sstone — APPROVED** [review]
