### PR TITLE
Index trampoline payments by hash and secret

### LINKED ISSUE #1723: NodeRelayer should index payments by `payment_hash || payment_secret`
Right now, the `NodeRelayer` indexes child actors by `payment_hash` only.
It means that senders must know beforehand the total amount they will send through each trampoline node.
This works fine for single-trampoline scenarios, but will not work with multi-trampoline scenarios: if the payer splits his payment between several trampoline routes and one fails, he may end up sending more additional HTLCs to a previous route when retrying.
Right now, we will reject them because the `payment_secret` doesn't match, or we'll simply fail to relay them (if the `payment_secret` is reused) and wait for a timeout from the final recipient.

We should instead index by `payment_hash || payment_secret`, but that requires extracting the `payment_secret` a bit higher up in our call stack.

### PR DESCRIPTION
**Pull request by t-bast**
We need to group incoming HTLCs together by `payment_hash` *and* `payment_secret`, otherwise we will reject valid payments that are split into multiple distinct trampoline parts (same `payment_hash` but different `payment_secret`).

Thanks @ecdsa for pointing out this issue.

Fixes #1723

### CODE REVIEW

File: eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala [hunk 1]
```diff
@@ -144,66 +161,37 @@ class NodeRelay private(nodeParams: NodeParams,
...
-  private def receiving(htlcs: Queue[UpdateAddHtlc], secret: ByteVector32, nextPayload: Onion.NodeRelayPayload, nextPacket: OnionRoutingPacket, handler: ActorRef): Behavior[Command] =
+  private def receiving(htlcs: Queue[UpdateAddHtlc], nextPayload: Onion.NodeRelayPayload, nextPacket: OnionRoutingPacket, handler: ActorRef): Behavior[Command] =
     Behaviors.receiveMessagePartial {
       case Relay(IncomingPacket.NodeRelayPacket(add, outer, _, _)) => outer.paymentSecret match {
+        // TODO: @pm: maybe those checks should be done by the mpp FSM?
         case None =>
-          context.log.warn("rejecting htlcId={}: missing payment secret", add.id)
+          context.log.warn("rejecting htlc #{} from channel {}: missing payment secret", add.id, add.channelId)
           rejectHtlc(add.id, add.channelId, add.amountMsat)
           Behaviors.same
```
Comment (pm47) [inline eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala:186]: Why keep this? We know it can't happen right?

File: eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala [hunk 2]
```diff
@@ -144,66 +161,37 @@ class NodeRelay private(nodeParams: NodeParams,
...
-        case Some(incomingSecret) if incomingSecret != secret =>
-          context.log.warn("rejecting htlcId={}: payment secret doesn't match other HTLCs in the set", add.id)
+        case Some(incomingSecret) if incomingSecret != paymentSecret =>
+          context.log.warn("rejecting htlc #{} from channel {}: payment secret doesn't match other HTLCs in the set", add.id, add.channelId)
           rejectHtlc(add.id, add.channelId, add.amountMsat)
           Behaviors.same
```
Comment (pm47) [inline eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala:190]: This cannot happen anymore either?

File: eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala [hunk 3]
```diff
@@ -48,34 +51,47 @@ object NodeRelayer {
...
-                context.log.debug(s"spawning a new handler with relayId=$relayId")
-                val outgoingPaymentFactory = NodeRelay.SimpleOutgoingPaymentFactory(nodeParams, router, register)
-                val handler = context.spawn(NodeRelay.apply(nodeParams, context.self, register, relayId, paymentHash, outgoingPaymentFactory), relayId.toString)
-                context.log.debug("forwarding incoming htlc to new handler")
-                handler ! NodeRelay.Relay(nodeRelayPacket)
-                apply(nodeParams, router, register, children + (paymentHash -> handler))
+                context.log.warn("rejecting htlc #{} from channel {}: missing payment secret", htlcIn.id, htlcIn.channelId)
+                val failureMessage = IncorrectOrUnknownPaymentDetails(htlcIn.amountMsat, nodeParams.currentBlockHeight)
+                val cmd = CMD_FAIL_HTLC(htlcIn.id, Right(failureMessage), commit = true)
+                PendingRelayDb.safeSend(register, nodeParams.db.pendingRelay, htlcIn.channelId, cmd)
```
[the remark this answers is not in the document]
Comment (t-bast) [reply eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala:88]: I think it would make sense, yes. It's been introduced in December 2019, so we can probably consider them mandatory now.
When we make that change, we should set the feature bit as mandatory. I added that to my TODO-list.

File: eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala [hunk 4]
```diff
@@ -29,16 +32,16 @@ import java.util.UUID
...
+ * It doesn't do the job itself, instead it dispatches each individual payment (which can be multi-in, multi-out) to a
+ * child actor of type [[NodeRelay]].
  */
 object NodeRelayer {
 
   // @formatter:off
   sealed trait Command
   case class Relay(nodeRelayPacket: IncomingPacket.NodeRelayPacket) extends Command
-  case class RelayComplete(childHandler: ActorRef[NodeRelay.Command], paymentHash: ByteVector32) extends Command
+  case class RelayComplete(childHandler: ActorRef[NodeRelay.Command], paymentHash: ByteVector32, paymentSecret: ByteVector32) extends Command
```
[the remark this answers is not in the document]
Comment (t-bast) [reply eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala:44]: I hesitated, it forces the `NodeRelay` child to know about a type that could be private to `NodeRelayer`...

File: eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala [hunk 5]
```diff
@@ -75,13 +76,29 @@ object NodeRelay {
     }
   }
 
-  def apply(nodeParams: NodeParams, parent: akka.actor.typed.ActorRef[NodeRelayer.Command], register: ActorRef, relayId: UUID, paymentHash: ByteVector32, outgoingPaymentFactory: OutgoingPaymentFactory): Behavior[Command] =
+  def apply(nodeParams: NodeParams,
+            parent: akka.actor.typed.ActorRef[NodeRelayer.Command],
+            register: ActorRef,
+            relayId: UUID,
+            nodeRelayPacket: NodeRelayPacket,
+            paymentSecret: ByteVector32,
```
[the remark this answers is not in the document]
Comment (t-bast) [reply eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala:84]: Definitely, will be cleaned up in a future change. I'll discuss it with other implementations as well to see where they stand on making it mandatory.

File: eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala [hunk 6]
```diff
@@ -144,66 +161,37 @@ class NodeRelay private(nodeParams: NodeParams,
...
-    context.messageAdapter[PaymentSent](WrappedPaymentSent)
-    context.messageAdapter[PaymentFailed](WrappedPaymentFailed)
-  }.toClassic
-
-  def apply(): Behavior[Command] =
-    Behaviors.receiveMessagePartial {
-      // We make sure we receive all payment parts before forwarding to the next trampoline node.
-      case Relay(IncomingPacket.NodeRelayPacket(add, outer, inner, next)) => outer.paymentSecret match {
-        case None =>
-          // TODO: @pm: maybe those checks should be done later in the flow (by the mpp FSM?)
```
[the remark this answers is not in the document]
Comment (t-bast) [reply eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala:168]: IIUC that comment was alluding to the fact that the MPP FSM doesn't check the `payment_secret` at all, and assumes it has been checked earlier. We *could* change that assumption in the MPP FSM, but I'd rather make `payment_secret` mandatory and simplify this altogether.

File: eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala (hunk 4 above)
[the remark this answers is not in the document]
Comment (pm47) [reply eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala:44]: Yes, let's forget it.

File: eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala (hunk 1 above)
Comment (t-bast) [reply eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala:186]: Yes, but at the type level it could (if we change the `NodeRelayer` code without updating the `NodeRelay`), so it's kind of a defense-in-depth to keep this handler (for now, let's get rid of all of them soon!)

File: eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala (hunk 2 above)
Comment (t-bast) [reply eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala:190]: Same reason, it doesn't cost much to handle this here and is a defense-in-depth, this way we don't need to make assumptions about how our parent behaves

File: eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala (hunk 1 above)
Comment (pm47) [reply eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala:186]: Another way to deal with that is to add a `require` when instantiating the actor, and then do `outer.paymentSecret.get` everywhere?

Comment (t-bast) [reply eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala:186]: I'll try that

Comment (t-bast) [reply eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala:186]: I'm not a big fan, it's less robust since we can cleanly handle this case in just a few lines of code without any risk of crashing the actor. I'd rather wait to make `payment_secret` mandatory to simplify this.

Comment (pm47) [reply eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala:186]: True, it's a bit dirty.

**Review by pm47 — APPROVED** [review]
