### PR TITLE
Better handling of invalid public keys in codecs

### LINKED ISSUE #3009: Node 0.10.x / 0.11.x stopped working after restart "requirement failed: public key is invalid"
I'm now on master and Bitcoin Core 28.1, same issue unfortunately.

### Discussed in https://github.com/ACINQ/eclair/discussions/3008

<div type='discussions-op-text'>

<sup>Originally posted by **EagleTM** February 15, 2025</sup>
Hi,
I'm running into a fatal issue on a bech32 wallet on 0.10.x with core 25.0 the error persists upon upgrading to 0.11.x with bitcoin core 27.2
The node was shutdown cleanly. Upon restart the error message is:

It never binds the ln port, so can't be queried further:

2025-02-15 17:01:17,722 INFO  fr.acinq.eclair.Setup - initial address=<redacted> for bitcoin wallet=eclair
2025-02-15 17:01:17,811 INFO  akka.actor.ActorCell - channels listener is ready
2025-02-15 17:01:17,871 ERROR a.a.OneForOneStrategy - requirement failed: public key is invalidjava.lang.IllegalArgumentException: requirement failed: public key is invalid
        at scala.Predef$.require(Predef.scala:337)
        at fr.acinq.bitcoin.scalacompat.Crypto$PublicKey$.fromBin(Crypto.scala:115)
        at fr.acinq.bitcoin.scalacompat.Crypto$PublicKey$.apply(Crypto.scala:111)
        at fr.acinq.eclair.wire.protocol.CommonCodecs$.$anonfun$publicKey$4(CommonCodecs.scala:167)
        at scodec.DecodeResult.map(DecodeResult.scala:17)
        at fr.acinq.eclair.wire.protocol.CommonCodecs$.$anonfun$publicKey$3(CommonCodecs.scala:167)
        at scodec.Attempt$Successful.map(Attempt.scala:111)
        at fr.acinq.eclair.wire.protocol.CommonCodecs$.$anonfun$publicKey$2(CommonCodecs.scala:167)
        at scodec.Codec$$anon$10.decode(Codec.scala:484)
        at scodec.Codec$$anon$7.decode(Codec.scala:411)
        at scodec.DecoderFunctions.decodeBothCombine(Decoder.scala:137)
        at scodec.DecoderFunctions.decodeBothCombine$(Decoder.scala:133)
        at scodec.Codec$.decodeBothCombine(Codec.scala:472)
        at scodec.codecs.HListCodec$$anon$2.decode(HListCodec.scala:22)
        at scodec.Codec$$anon$2.decode(Codec.scala:201)
        at scodec.DecoderFunctions.decodeCollect(Decoder.scala:184)
        at scodec.DecoderFunctions.decodeCollect$(Decoder.scala:175)
        at scodec.Decoder$.decodeCollect(Decoder.scala:228)
        at scodec.codecs.ListCodec.decode(ListCodec.scala:16)
        at scodec.Decoder$$anon$1.decode(Decoder.scala:48)
        at scodec.GenCodec$$anon$2.decode(GenCodec.scala:78)
        at scodec.Decoder$$anon$2.$anonfun$decode$2(Decoder.scala:57)
        at scodec.Attempt$Successful.flatMap(Attempt.scala:113)
        at scodec.Decoder$$anon$2.decode(Decoder.scala:56)

I tried starting with elcair network database moved to backup, no difference
I'm at loss what the issue could be - I'm assuming it has issues parsing bitcoin-core wallet pubkeys rather than ln pubkeys.

Any  ideas what I could do to debug this further?

</div>

### PR DESCRIPTION
**Pull request by t-bast**
We try to ensure that our codecs never throw, and instead return an `Attempt.Failure` instance when data cannot be decoded to the expected format. However, we don't have a good fuzzing infrastructure in place, so we cannot ensure that this assumption is met. It is thus safer to wrap decoding into a `try/catch` statement: as far as I can tell, it should only have a performance impact when an exception is thrown, otherwise the impact is negligible.

We already do this when decoding lightning messages received from the wire: the only cases I could identify where this issue happens if for trampoline payments with an invalid public key and invalid blinded path encoded nodeIDs.

Fixes #3009

### CODE REVIEW

File: eclair-core/src/main/scala/fr/acinq/eclair/message/OnionMessages.scala [hunk 1]
```diff
@@ -166,10 +167,11 @@ object OnionMessages {
...
       case Right(p: Sphinx.DecryptedPacket) =>
-        MessageOnionCodecs.perHopPayloadCodec.decode(p.payload.bits) match {
-          case Attempt.Successful(DecodeResult(perHopPayload, _)) if p.isLastPacket => Right(DecodedOnionPacket(perHopPayload, None))
-          case Attempt.Successful(DecodeResult(perHopPayload, _)) => Right(DecodedOnionPacket(perHopPayload, Some(p.nextPacket)))
-          case Attempt.Failure(f) => Left(CannotDecodeOnion(f.message))
+        Try(MessageOnionCodecs.perHopPayloadCodec.decode(p.payload.bits)) match {
+          case Success(Attempt.Successful(DecodeResult(perHopPayload, _))) if p.isLastPacket => Right(DecodedOnionPacket(perHopPayload, None))
+          case Success(Attempt.Successful(DecodeResult(perHopPayload, _))) => Right(DecodedOnionPacket(perHopPayload, Some(p.nextPacket)))
+          case Success(Attempt.Failure(f)) => Left(CannotDecodeOnion(f.message))
+          case Failure(f) => Left(CannotDecodeOnion(s"unexpected exception in onion message codecs: ${f.getMessage}"))
```
Comment (pm47) [inline eclair-core/src/main/scala/fr/acinq/eclair/message/OnionMessages.scala:174]: Looking at scodec's code, they do explicitly call `try`/`catch` in risky codecs (e.g. [StringCodec](https://github.com/scodec/scodec/blob/5d6d0fb24e9ea1eeec4aa7f604efe179ce5ce463/shared/src/main/scala/scodec/codecs/StringCodec.scala)). Shouldn't we do the same ourselves and ensure that those return proper `Attempt.Failure` instead of wrapping everything inside a `try`/`catch`? I think that `Attempt.fromTry` is designed for that purpose.

**Review by pm47 — APPROVED** [review]
